package tool;

import db.obj.Pair;
import org.jetbrains.annotations.NonNls;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.Properties;

import static tool.Tools.forceRun;

/**
 * Translated from Frice-Engine
 * Created by ice1000 on 2016/8/20.
 *
 * @author ice1000
 */
@SuppressWarnings("WeakerAccess")
public class Configurations {
	@NotNull
	private final File file;
	@NotNull
	private final Properties properties;
	@Nullable
	private static Configurations sharedInstance;

	@NotNull
	public static Configurations getSharedInstance() {
		if (sharedInstance == null) sharedInstance = new Configurations();
		return sharedInstance;
	}

	@SuppressWarnings("ResultOfMethodCallIgnored")
	public Configurations() {
		this("res/config.conf");
	}

	public Configurations(@NotNull File file) {
		this.file = file;
		properties = new Properties();
		if (!file.exists()) forceRun(file::createNewFile);
		forceRun(() -> properties.load(new FileInputStream(file)));
	}

	public Configurations(@NotNull @NonNls String file) {
		this(new File(file));
	}

	public void insert(@NotNull Pair pair) {
		insert(pair.getKey(), pair.getValue());
	}

	public void insert(@NotNull @NonNls String key, @NotNull @NonNls String value) {
		properties.setProperty(key, value);
		save();
	}

	private void save() {
		try {
			properties.store(new FileOutputStream(file), "Automatically generated by ice1000 Frice Engine");
		} catch (IOException ignored) {
		}
	}

	@Nullable
	@NonNls
	public String query(@NotNull @NonNls String key) {
		return properties.getProperty(key);
	}

	public void clear() {
		properties.clear();
		save();
	}
}
